# Sourced from: https://dzone.com/articles/continuous-integration-amp-delivery-for-microservi

version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Starting Java Build...
      - mvn clean
      - mvn install
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"Coco-API-container","imageUri":"783032674095.dkr.ecr.us-east-1.amazonaws.com/jro/quote-service:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
