# Sourced from: https://dzone.com/articles/continuous-integration-amp-delivery-for-microservi

version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Starting Java Build...
      - mvn clean
      - mvn install
