branch-defaults:
  master:
    environment: null
    group_suffix: null
deploy:
  artifact: target/quote-api-eb.jar
global:
  application_name: quote-service
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
